---
title: "curves"
author: "Maxwel Coura Oliveira"
date: "12/6/2021"
output: html_document
---

```{r}
library(tidyverse)
library(drc)
library(reactable)
library(ggthemes)
library(ggtext)
library(patchwork)
library(ggrepel)
```

# Lincoln


```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "Lincoln") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:9) %>% 
  pivot_longer(cols = 2:9, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - Apr 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "Lincoln") %>% 
  filter(!is.na(GDD)) -> lcn1
```


```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "Lincoln") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(13:21) %>% 
  pivot_longer(cols = 2:9, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2017-Jun 2018") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "Lincoln") %>% 
  filter(!is.na(GDD)) -> lcn2
```

```{r}
lcn1 %>% 
  bind_rows(lcn2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> lincoln
```

## Corn 

```{r message = FALSE, warning = FALSE}
lincoln |> 
  filter(type == "corn") -> crn_l

model1 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA)),
              data = crn_l)


```

```{r}
mse <- mean(residuals(model1)^2/df.residual(model1))
rmse <- sqrt(mse)
rmse
```

```{r}
plot(model1, col = c(4,2,3,5), type = "all")
abline(v = 100, h = 89.57)
```

```{r}
b <- -1.74426
d <- 100
c <- 0
e <- 80.75571
x <- 500

c + (d - 0) * exp(-exp(b*(log(x)-e)))
```


```{r}
summary(model1)
```



```{r}
broom::tidy(model1) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```
```{r}
ED(model1, c(10, 50, 90), type = "relative", interval = "delta")
```


```{r}
ED(model1, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed2
```


```{r}
EDcomp(model1, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```

```{r}
ed2 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10%",
  ed == "50" ~ "50%",
  ed == "90" ~ "90%",
  TRUE ~ "ed")) |> 
  mutate(crop = "Corn") -> ed3
```


## Soybean 

```{r message = FALSE, warning = FALSE}
lincoln |> 
  filter(type == "soybean") -> soy_l

model2 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = soy_l)
```

```{r}
mse <- mean(residuals(model2)^2/df.residual(model1))
rmse <- sqrt(mse)
rmse
```

```{r}
plot(model2, col = c(4,2,3,5))
```

```{r}
broom::tidy(model2) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```


```{r}
ED(model2, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed5
```


```{r}
EDcomp(model2, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```

```{r}
ed5 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10%",
  ed == "50" ~ "50%",
  ed == "90" ~ "90%",
  TRUE ~ "ed")) |> 
  mutate(crop = "Soybean") -> ed6
```


## Curve Corn


```{r Control prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(1600), length=1600)))
newdata1 <- data.frame(population = c("Lin"), newdata)
newdata2 <- data.frame(population = c("Npl"), newdata)
newdata3 <- data.frame(population = c("Scb"), newdata)
newdata4 <- data.frame(population = c("Natural"), newdata)

nd <- rbind(newdata1, newdata2, newdata3, newdata4)

pm <- predict(model1, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

crn_l$GDD0 <- crn_l$GDD
crn_l$GDD0[crn_l$GDD0==0] <- 0.5
```




## Curve Soybean


```{r Control prediction, include=FALSE}
#newdata <- expand.grid(GDD=exp(seq(log(0.5), log(1600), length=1600)))
newdata5 <- data.frame(population =c("Lin"), newdata)
newdata6 <- data.frame(population =c("Npl"), newdata)
newdata7 <- data.frame(population =c("Scb"), newdata)
newdata8 <- data.frame(population = c("Natural"), newdata)

nd1 <- rbind(newdata5, newdata6, newdata7, newdata8)

pm1 <- predict(model2, newdata=nd1, interval="confidence")

nd1$p <- pm1[,1] 
nd1$pmin <- pm1[,2] 
nd1$pmax <- pm1[,3] 

soy_l$GDD0 <- soy_l$GDD
soy_l$GDD0[soy_l$GDD0==0] <- 0.5
```





```{r message=FALSE, warning=FALSE}
crn_l |> 
  bind_rows(soy_l) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#009E73;'>Natural</b>" = "Natural",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) |> 
  rename(crop = type) |> 
  mutate(crop = str_to_title(crop)) -> full_dt2

nd |> 
  mutate(crop = "Corn") -> nd

nd1 |> 
  mutate(crop = "Soybean") -> nd1

nd |> 
  bind_rows(nd1) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#009E73;'>Natural</b>" = "Natural",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) -> nd2
```


```{r message=FALSE, warning=FALSE}
full_dt2 %>% 
ggplot(aes(x = GDD, y = emergence, color = population)) + 
  geom_jitter(data = full_dt2, 
              aes(x = GDD, y = emergence, color = population),
              alpha = 0.1) +
  geom_line(data = nd2, aes(x = GDD, y = p, color = population), size = 1) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
  coord_trans(x= "log") +
#  geom_point(alpha = 0.1) +
  facet_grid(crop ~ location) +
  scale_x_continuous(limits = c(1, 5000), breaks = c(1, 10, 100, 1000)) + 
  scale_color_manual(name = "Accession", 
                     values = c("#000000", "#009E73", "#E69F00", "#56B4E9"),
                         guide = guide_legend(reverse = TRUE)) +
  geom_segment(aes(x = 25, y = 10,
                   xend = 400, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 0.8,
               color = 2) +
  annotate("text", x = 700, y = 10, label = "10%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 70, y = 50, 
                   xend = 750, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 1350, y = 50, label = "50%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 200, y = 90, 
                   xend = 2000, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 3500, y = 90, label = "90%", 
           fontface = 'italic', color = "#333333",
           size = 3) +
  theme_bw() +
  theme(axis.title = element_markdown(size = 14),
        axis.text = element_markdown(size = 13),
        legend.position = c(0.2, 0.9),
        legend.title = element_markdown(size = 14, face = "italic"),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        panel.grid = element_blank(),
        legend.text = element_markdown(size = 11, face = "bold"),
        legend.key.size = unit(0.5, "cm"),
        strip.text = element_markdown(size = 14, face = "bold")) -> fig3

ggsave("figures/fig_99.png", dpi = 300, width = 4, height = 7)
```



## North Platte


```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "North Platte") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - May 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "North Platte") %>% 
  filter(!is.na(GDD)) -> np1
```


```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "North Platte") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(5:8) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - May 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "North Platte") %>% 
  filter(!is.na(GDD)) -> np2
```



```{r}
np1 %>% 
  bind_rows(np2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> north_platte
```

## Wheat stubble


```{r message = FALSE, warning = FALSE}
wheat_m <- north_platte |> 
  filter(type == "wheat stubble")

model3 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = wheat_m)
```

```{r}
mse <- mean(residuals(model3)^2/df.residual(model3))
rmse <- sqrt(mse)
rmse
```

```{r}
broom::tidy(model3) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

```{r}
plot(model3, type = "all")
```


  
```{r}
ED(model3, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) -> ed3
```

```{r}
EDcomp(model3, c(10,10, 50, 50, 90,90), type = "absolute", 
       ilevel = 0.95)
```

```{r warning = FALSE}
ed3 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10%",
  ed == "50" ~ "50%",
  ed == "90" ~ "90%",
  TRUE ~ "ed")) |> 
  mutate(crop = "Wheat stubble") -> ed4
```


## Soybean


```{r message = FALSE, warning = FALSE}
soy_m <- north_platte |> 
  filter(type == "soybean")

model4 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = soy_m)
```

```{r}
mse <- mean(residuals(model4)^2/df.residual(model4))
rmse <- sqrt(mse)
rmse
```

```{r}
broom::tidy(model4) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

```{r}
plot(model4, type = "all")
```


  
```{r}
ED(model4, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) -> ed5
```

```{r}
EDcomp(model4, c(10,10, 50,50, 90,90), type = "absolute", 
       level = 0.95)
```

```{r warning = FALSE}
ed5 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10%",
  ed == "50" ~ "50%",
  ed == "90" ~ "90%",
  TRUE ~ "ed")) |> 
  mutate(crop = "Soybean") -> ed6
```


## Curve Wheat stubble


```{r Control prediction, include=FALSE}
#newdata <- expand.grid(GDD=exp(seq(log(0.5), log(1500), length=1500)))
newdata1 <- data.frame(population = c("Lin"), newdata)
newdata2 <- data.frame(population = c("Npl"), newdata)
newdata3 <- data.frame(population = c("Scb"), newdata)

nd <- rbind(newdata1, newdata2, newdata3)

pm <- predict(model3, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

wheat_m$GDD0 <- wheat_m$GDD
wheat_m$GDD0[wheat_m$GDD0==0] <- 0.5
```


## Curve Soybean


```{r Control prediction, include=FALSE}
#newdata <-  expand.grid(GDD=exp(seq(log(0.5), log(1500), length=1500)))
newdata4 <- data.frame(population =c("Lin"), newdata)
newdata5 <- data.frame(population =c("Npl"), newdata)
newdata6 <- data.frame(population =c("Scb"), newdata)

nd1 <- rbind(newdata4, newdata5, newdata6)

pm1 <- predict(model4, newdata=nd1, interval="confidence")

nd1$p <- pm1[,1] 
nd1$pmin <- pm1[,2] 
nd1$pmax <- pm1[,3] 

soy_m$GDD0 <- soy_m$GDD
soy_m$GDD0[soy_m$GDD0==0] <- 0.5
```



```{r message=FALSE, warning=FALSE}
wheat_m |> 
  bind_rows(soy_m) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) |> 
  rename(crop = type) |> 
  mutate(crop = str_to_sentence(crop)) -> full_dt1

nd |> 
  mutate(crop = "Wheat stubble") -> nd

nd1 |> 
  mutate(crop = "Soybean") -> nd1

nd |> 
  bind_rows(nd1) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) -> nd2
```


```{r message=FALSE, warning=FALSE}
full_dt1 %>% 
ggplot(aes(x = GDD, y = emergence, color = population)) + 
  geom_jitter(data = full_dt1, 
              aes(x = GDD, y = emergence, color = population),
              alpha = 0.1) +
  geom_line(data = nd2, aes(x = GDD, y = p, color = population), size = 1) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
  coord_trans(x= "log") +
#  geom_point(alpha = 0.1) +
  facet_grid(crop ~ location) +
  scale_x_continuous(limits = c(1, 5000), breaks = c(1, 10, 100, 1000)) + 
  scale_color_colorblind(name = NULL, 
                         guide = guide_legend(reverse = TRUE)) +
  geom_segment(aes(x = 25, y = 10,
                   xend = 400, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 0.8,
               color = 2) +
  annotate("text", x = 700, y = 10, label = "10%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 70, y = 50, 
                   xend = 750, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 1350, y = 50, label = "50%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 200, y = 90, 
                   xend = 2000, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 3500, y = 90, label = "90%", 
           fontface = 'italic', color = "#333333",
           size = 3) +
  theme_bw() +
  theme(axis.title = element_markdown(size = 14),
        axis.text = element_markdown(size = 13),
        legend.position = "none",
        legend.title = element_markdown(size = 14, face = "italic"),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        panel.grid = element_blank(),
        legend.text = element_markdown(size = 11, face = "bold"),
        legend.key.size = unit(0.5, "cm"),
        strip.text = element_markdown(size = 14, face = "bold")) -> fig4

ggsave("figures/fig_22.png", dpi = 300, width = 4, height = 7)
```



# Scottsbluff

```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - Apr 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") %>% 
  filter(!is.na(GDD)) -> sctbf1
```

```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(7:13) %>% 
  pivot_longer(cols = 2:7, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2017 - Dec 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") -> sctbf2
```

```{r}
sctbf1 %>% 
  bind_rows(sctbf2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  mutate(type = fct_recode(type,
                           "corn" = "irrigated")) |> 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> scottsbluff
```

## Corn


```{r message = FALSE, warning = FALSE}
crn_scott <- scottsbluff |> 
  filter(type == "corn")

model5 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA)),
              data = crn_scott)
```

```{r}
mse <- mean(residuals(model5)^2/df.residual(model5))
rmse <- sqrt(mse)
rmse
```

```{r}
broom::tidy(model5) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

```{r}
plot(model5)
```

```{r}
broom::tidy(model5) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

```{r}
ED(model5, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed1
```



```{r}
readxl::read_excel("data/dates.xlsx", sheet = "Scottsbluff") %>% 
  drop_na() %>% 
  mutate(month = lubridate::month(date),
         doy = lubridate::yday(date)) -> date_sct
```


```{r warning = FALSE}
ed1 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10%",
  ed == "50" ~ "50%",
  ed == "90" ~ "90%",
  TRUE ~ "ed")) |> 
  mutate(crop = "Corn") -> ed2
```


## Fallow

```{r message = FALSE, warning = FALSE}
fallow_scott <- scottsbluff |> 
  filter(type == "fallow")

model6 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA)),
              data = fallow_scott)
```

```{r}
mse <- mean(residuals(model6)^2/df.residual(model6))
rmse <- sqrt(mse)
rmse
```


```{r}
plot(model6, type = "all")
```

```{r}
broom::tidy(model6) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

```{r}
ED(model6, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed3
```

```{r}
EDcomp(model6, c(10,10, 50,50, 90,90), type = "absolute", 
       level = 0.95)
```

```{r warning = FALSE}
ed3 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10%",
  ed == "50" ~ "50%",
  ed == "90" ~ "90%",
  TRUE ~ NA_character_)) |> 
  mutate(crop = "Fallow") -> ed4
```




## Curve Corn


```{r Control prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(760), length=760)))
newdata1 <- data.frame(population = c("Lin"), newdata)
newdata2 <- data.frame(population = c("Npl"), newdata)
newdata3 <- data.frame(population = c("Scb"), newdata)

nd <- rbind(newdata1, newdata2, newdata3)

pm <- predict(model5, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

crn_scott$GDD0 <- crn_scott$GDD
crn_scott$GDD0[crn_scott$GDD0==0] <- 0.5
```


## Curve Fallow


```{r Control prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(760), length=760)))
newdata4 <- data.frame(population =c("Lin"), newdata)
newdata5 <- data.frame(population =c("Npl"), newdata)
newdata6 <- data.frame(population =c("Scb"), newdata)

nd1 <- rbind(newdata4, newdata5, newdata6)

pm1 <- predict(model6, newdata=nd1, interval="confidence")

nd1$p <- pm1[,1] 
nd1$pmin <- pm1[,2] 
nd1$pmax <- pm1[,3] 

fallow_scott$GDD0 <- fallow_scott$GDD
fallow_scott$GDD0[fallow_scott$GDD0==0] <- 0.5
```

```{r Control Plot, message=FALSE, warning=FALSE}
crn_scott |> 
  bind_rows(fallow_scott) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) |> 
  rename(crop = type) |> 
  mutate(crop = str_to_title(crop)) -> full_dt

nd |> 
  mutate(crop = "Corn") -> nd

nd1 |> 
  mutate(crop = "Fallow") -> nd1

nd |> 
  bind_rows(nd1) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) -> nd2
```


```{r message=FALSE, warning=FALSE}
full_dt %>% 
ggplot(aes(x = GDD, y = emergence, color = population)) + 
  geom_jitter(data = full_dt, 
              aes(x = GDD, y = emergence, color = population),
              alpha = 0.1) +
  geom_line(data = nd2, aes(x = GDD, y = p, color = population), size = 1) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
  coord_trans(x= "log") +
#  geom_point(alpha = 0.1) +
  facet_grid(crop ~ location) +
  scale_x_continuous(limits = c(1, 5000), breaks = c(1, 10, 100, 1000)) + 
  scale_color_colorblind(name = NULL, 
                         guide = guide_legend(reverse = TRUE)) +
  geom_segment(aes(x = 30, y = 10,
                   xend = 120, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 0.8,
               color = 2) +
  annotate("text", x = 200, y = 10, label = "10%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 50, y = 50, 
                   xend = 155, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 280, y = 50, label = "50%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 100, y = 90, 
                   xend = 255, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 415, y = 90, label = "90%", 
           fontface = 'italic', color = "#333333",
           size = 3) +
  theme_bw() +
  theme(axis.title = element_markdown(size = 14),
        axis.text = element_markdown(size = 13),
        legend.position = "none",
        legend.title = element_markdown(size = 14, face = "italic"),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        panel.grid = element_blank(),
        legend.text = element_markdown(size = 11, face = "bold"),
        legend.key.size = unit(0.5, "cm"),
        strip.text = element_markdown(size = 14, face = "bold")) -> fig5

ggsave("figures/fig_2.png", dpi = 300, width = 4, height = 7)
```




```{r warning = FALSE}
fig3 + fig4 + fig5 +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 15, hjust = 0, vjust = 0),
        panel.background = element_rect(fill = "#F5F5F5"),
        plot.background = element_rect(fill = "#F5F5F5"))

ggsave("figures/Final.png", width = 13, height = 7) 
```





