---
title: "dates"
author: "Maxwel Coura Oliveira"
date: "6/30/2021"
output: html_document
---

```{r}
library(tidyverse)
```

## Scottsbluff

```{r}
readxl::read_excel("Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - Apr 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") %>% 
  filter(!is.na(GDD)) -> sctbf1
```

```{r}
readxl::read_excel("Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(7:13) %>% 
  pivot_longer(cols = 2:7, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2017 - Dec 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") -> sctbf2
```


```{r}
sctbf1 %>% 
  bind_rows(sctbf2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> scottsbluff
```



```{r echo = TRUE}
model1 <- drm(emergence ~ GDD, trt, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = scottsbluff)
```



```{r include=FALSE}
ED(model1, c(10, 50, 90), interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "Term") %>% 
  mutate_if(is.double, ~ round(., 4)) -> ed_sct
```


```{r}
readxl::read_excel("dates.xlsx", sheet = "Scottsbluff") %>% 
  drop_na() %>% 
  mutate(month = lubridate::month(date),
         doy = lubridate::yday(date)) -> date_sct
```


```{r}
date_sct %>% 
  ggplot(aes(x = month, y = gdd)) +
  geom_point()
```

