---
title: "Marestail emergence in Nebraska"
author: "Maxwel Coura Oliveira"
date: "6/24/2021"
output: html_document
---


```{r}
library(tidyverse)
library(drc)
library(reactable)
library(ggthemes)
library(ggtext)
library(patchwork)
```

# Scottsbluff

```{r}
readxl::read_excel("Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - Apr 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") %>% 
  filter(!is.na(GDD)) -> sctbf1
```


```{r}
readxl::read_excel("Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(7:13) %>% 
  pivot_longer(cols = 2:7, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2017 - Dec 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") -> sctbf2
```


```{r}
sctbf1 %>% 
  bind_rows(sctbf2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> scottsbluff
```

```{r message = FALSE, warning = FALSE}
model2 <- drm(emergence ~ GDD, trt, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = scottsbluff)
```

```{r}
plot(model2)
```

```{r}
broom::tidy(model2) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

```{r}
ED(model2, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed2
```

```{r}
EDcomp(model2, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```


```{r}
ed2 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10% emergence",
  ed == "50" ~ "50% emergence",
  ed == "90" ~ "90% emergence",
  TRUE ~ "ed")) %>% 
  ggplot(aes(x = population, y = estimate, color = trt)) +
  geom_point(position = position_dodge(width = 0.7)) +
  geom_linerange(aes(ymin = lower, ymax = upper), 
                 position = position_dodge(width = 0.7)) +
  labs(x = NULL, y = "Growing degree days"#,
#       title = "Horseweed emergence in <b style='color:#0000ff;'>wheat stubble</b> and <b style='color:#b02631;'>soybean</b> at North Platte, NE",
#       subtitle = "Horseweed accessions comulative emergence was recorded from Sep 2016 to May 2017"
) +
  scale_color_brewer(palette = "Set1") +
#  scale_color_viridis_d(name = NULL, option = "G") +
  facet_grid(~ ed, switch = "y") +
  coord_flip() +
  theme_few() +
#  scale_y_continuous(limits = c(0, 1500)) +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9),
        strip.text = element_markdown(face = "italic"),
        plot.title.position = "plot",
        plot.title = element_markdown(),
        plot.subtitle = element_markdown(size = 10)) -> fig1

ggsave("figures/fig_1.png", dpi = 300)
```


```{r Control prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(760), length=760)))
newdata1 <- data.frame(trt =c("Lin1 in fallow"), newdata)
newdata2 <- data.frame(trt =c("Lin1 in irrigated"), newdata)
newdata3 <- data.frame(trt =c("Npl1 in fallow"), newdata)
newdata4 <- data.frame(trt =c("Npl1 in irrigated"), newdata)
newdata5 <- data.frame(trt =c("Scb1 in fallow"), newdata)
newdata6 <- data.frame(trt =c("Scb1 in irrigated"), newdata)

nd=rbind(newdata1, newdata2, newdata3, newdata4, newdata5, newdata6)

pm <- predict(model2, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

scottsbluff$GDD0 <- scottsbluff$GDD
scottsbluff$GDD0[scottsbluff$GDD0==0] <- 0.5
```


```{r Control Plot, message=FALSE, warning=FALSE}
scottsbluff %>% 
ggplot(aes(x = GDD, y = emergence, color = trt)) + 
  geom_line(data = nd, aes(x = GDD, y = p, color = trt), size = 1.2) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
#  coord_trans(x= "log") +
  geom_jitter(data = scottsbluff, aes(x = GDD, y = emergence, color = trt),
              alpha = 0.1) +
  scale_color_brewer(name = NULL, palette = "Set1") +
#  scale_color_viridis_d(name = NULL, option = "C") +
  geom_segment(aes(x = 20, y = 10, 
                   xend = 120, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 1.05,
               color = "blue") +
  annotate("text", x = 280, y = 10, label = "10% emergence", 
           fontface = 'italic',
           size = 2.7) +
  geom_segment(aes(x = 45, y = 50, 
                   xend = 150, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 1.05,
               color = "blue") +
  annotate("text", x = 310, y = 50, label = "50% emergence", 
           fontface = 'italic',
           size = 2.7) +
  geom_segment(aes(x = 100, y = 90, 
                   xend = 250, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 1.05,
               color = "blue") +
  annotate("text", x = 410, y = 90, label = "90% emergence", 
           fontface = 'italic',
           size = 2.7) +
  theme_few() +
  theme(axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9),
        legend.position = c(0.8, 0.2),
        legend.text = element_text(size = 5),
        legend.key.size = unit(0.3, "cm")) -> fig2

ggsave("figures/fig_2.png")
```


```{r}
readxl::read_excel("Scottsbluff Marestail.xlsx", sheet = "Weather Yr1") %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  rename(
    temp_high = c,
    temp_low = c_2,
    rel_hum = percent,
    precip = mm,
    wind_sp = m_s,
    soil_temp = c_10cm
  ) %>% 
  dplyr::select(-mj_m_2, -mm_2, -time) %>% 
  unite("date", c("year", "month", "day"), sep = "-") %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  mutate_if(is_character, as.double) -> wd_sct1

readxl::read_excel("Scottsbluff Marestail.xlsx", sheet = "Weather Yr2") %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  rename(
    temp_high = c,
    temp_low = c_2,
    rel_hum = percent,
    precip = mm,
    wind_sp = m_s,
    soil_temp = c_10cm
  ) %>% 
  dplyr::select(-mj_m_2, -mm_2, -time) %>% 
  unite("date", c("year", "month", "day"), sep = "-") %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  mutate_if(is_character, as.double) -> wd_sct2


wd_sct1 %>% 
  bind_rows(wd_sct2) %>% 
  mutate(mean_temp = (temp_high + temp_low) / 2) %>% 
  pivot_longer(cols = c("mean_temp", "soil_temp"), 
               names_to = "type", values_to = "temp") -> wd_sct
```

```{r}
ylim.prim <- c(0, 180)   # in this example, precipitation
ylim.sec <- c(-27, 36)    # in this example, temperature

b <- diff(ylim.prim)/diff(ylim.sec)
a <- ylim.prim[1] - b*ylim.sec[1] # there was a bug here
```


```{r}
wd_sct %>% 
  mutate(type = fct_recode(type,
                           "Air temperature (C)" = "mean_temp",
                           "Soil temperature (C)" = "soil_temp")) %>% 
  ggplot(aes(x = date, y = a + temp*b)) +
  geom_rect(mapping=aes(xmin= as.Date("2016-08-30"), xmax= as.Date("2017-04-03"),
                        ymin= 0, ymax= 160), 
            fill = "#FFFDD0", alpha=0.05) + 
  annotate("text", x=as.Date("2016-12-15"), y = 155, 
           label = "Year 1",
           size = 2, color = "black") + 
  geom_rect(mapping=aes(xmin= as.Date("2017-09-25"), xmax= as.Date("2017-12-31"),
                        ymin= 0, ymax= 160), 
            fill = "#FFFDD0", alpha=0.05) + 
  annotate("text", x=as.Date("2017-11-20"), y = 155, 
           label = "Year 2", face = "bold",
           size = 2, color = "black") + 
  geom_point(aes(color = type), size = 1, alpha = 0.5) +
  geom_line(aes(color = type, linetype = type), size = .3) +
  scale_color_manual(name = NULL, values = c("blue", "firebrick")) +
  scale_shape_manual(name = NULL, values = c(18, 16)) +
  scale_linetype_manual(name = NULL, values = c(3, 1)) +
  scale_y_continuous(
    "Precipitation (mm)", 
    sec.axis = sec_axis(~ (. - a)/b, name = "Temperature (C)")) +
  scale_x_date(date_minor_breaks = "1 day", date_labels = "%b %Y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_bar(aes(x = date, y = precip, 
               width = 3,
               linetype = NULL, 
               shape = NULL), 
           stat = "identity", 
           fill = "grey10",
           show.legend = FALSE) +
  annotate("text", x=as.Date("2016-08-30"), y = 55, 
           label = "Precipitation",
           size = 2, color = "grey10") +
  annotate("text", x=as.Date("2017-07-15"), y = 80, 
           label = "Mean\n air temperature",
           size = 2, color = "blue") +
  annotate("text", x=as.Date("2018-01-15"), y = 140, 
           label = "Mean\n soil temperature",
           size = 2, color = "firebrick") +
  labs(x = NULL) +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9)) -> fig3

ggsave("figures/fig_3.png")
```


```{r}
library(extrafont)
library(showtext)
showtext_auto()
font_add_google("Roboto", "roboto") 
```


```{r}
fig3 + fig2 -> figg

fig_st <- figg / fig1 +
  plot_annotation(title = "<b style='color:darkgreen;'>Horseweed</b> emergence in irrigated and fallow at Scottsbluff, NE",
       subtitle = "Comulative emergence was recorded from Sep 2016 to Apr 2017 (Year 1) and Sep 2017 to Dec 2017 (Year 2)",
       theme = theme(plot.title = element_markdown(hjust = 0, 
                                                   family = "roboto",
                                                   size = 15),
                     plot.subtitle = element_markdown(family = "roboto",
                                                      size = 10),
                     plot.title.position = "plot")) 

ggsave("figures/scottsbluff.png", width = 7)
```


# Lincoln


```{r}
readxl::read_excel("Emergence.xlsx", sheet = "Lincoln") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:9) %>% 
  pivot_longer(cols = 2:9, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - Apr 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "Lincoln") %>% 
  filter(!is.na(GDD)) -> lcn1
```


```{r}
readxl::read_excel("Emergence.xlsx", sheet = "Lincoln") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(13:21) %>% 
  pivot_longer(cols = 2:9, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2017-Jun 2018") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "Lincoln") %>% 
  filter(!is.na(GDD)) -> lcn2
```


```{r}
lcn1 %>% 
  bind_rows(lcn2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> lincoln
```


```{r message = FALSE, warning = FALSE}
model1 <- drm(emergence ~ GDD, trt, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = lincoln)
```

```{r}
plot(model1, col = c(1,2,3,4,5,6,7,8))
```

```{r}
broom::tidy(model1) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```


```{r}
ED(model1, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed1
```


```{r}
EDcomp(model1, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```


```{r}
ed1 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10% emergence",
  ed == "50" ~ "50% emergence",
  ed == "90" ~ "90% emergence",
  TRUE ~ "ed")) %>% 
  mutate(population = fct_relevel(population, 
                                  levels = c("Lin1", "Npl1", "Scb1","Natural"))) %>% 
  ggplot(aes(x = population, y = estimate, color = trt)) +
  geom_point(position = position_dodge(width = 0.7)) +
  geom_linerange(aes(ymin = lower, ymax = upper), 
                 position = position_dodge(width = 0.7)) +
  labs(x = NULL, y = "Growing degree days"#,
#       title = "Horseweed emergence in <b style='color:#0000ff;'>wheat stubble</b> and <b style='color:#b02631;'>soybean</b> at North Platte, NE",
#       subtitle = "Horseweed accessions comulative emergence was recorded from Sep 2016 to May 2017"
) +
  scale_color_brewer(palette = "Paired") +
#  scale_color_viridis_d(name = NULL, option = "C") +
  facet_grid(~ ed, switch = "y") +
  coord_flip() +
  theme_few() +
  scale_y_continuous(limits = c(0, 600)) +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9),
        strip.text = element_markdown(face = "italic"),
        plot.title.position = "plot",
        plot.title = element_markdown(),
        plot.subtitle = element_markdown(size = 10)) -> fig1

ggsave("figures/fig_4.png", dpi = 300)
```
```{r}
ed1
```


```{r control-prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(1700), length=1700)))
newdata1 <- data.frame(trt =c("Lin1 in corn"), newdata)
newdata2 <- data.frame(trt =c("Lin1 in soybean"), newdata)
newdata3 <- data.frame(trt =c("Npl1 in corn"), newdata)
newdata4 <- data.frame(trt =c("Npl1 in soybean"), newdata)
newdata5 <- data.frame(trt =c("Scb1 in corn"), newdata)
newdata6 <- data.frame(trt =c("Scb1 in soybean"), newdata)
newdata7 <- data.frame(trt =c("Natural in corn"), newdata)
newdata8 <- data.frame(trt =c("Natural in soybean"), newdata)

nd = rbind(newdata1, newdata2, newdata3, newdata4, newdata5, newdata6, newdata7, newdata8)

pm <- predict(model1, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

lincoln$GDD0 <- lincoln$GDD
lincoln$GDD0[lincoln$GDD0==0] <- 0.5
```


```{r Control Plot, message=FALSE, warning=FALSE}
lincoln %>% 
    mutate(population = fct_relevel(population, 
                                  levels = c("Lin1", "Npl1", "Scb1","Natural"))) %>% 
ggplot(aes(x = GDD, y = emergence, color = trt)) + 
#  coord_trans(x= "log") +
  geom_jitter(data = lincoln, aes(x = GDD, y = emergence, color = trt),
              alpha = 0.1) +
  geom_line(data = nd, aes(x = GDD, y = p, color = trt), size = 1.2) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
  scale_color_brewer(name = NULL, palette = "Paired") +
#  scale_color_viridis_d(name = NULL, option = "C") +
  geom_segment(aes(x = 20, y = 10, 
                   xend = 190, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 1.05,
               color = "blue") +
  annotate("text", x = 570, y = 10, label = "10% emergence", 
           fontface = 'italic',
           size = 2.7) +
  geom_segment(aes(x = 45, y = 50, 
                   xend = 260, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 1.05,
               color = "blue") +
  annotate("text", x = 640, y = 50, label = "50% emergence", 
           fontface = 'italic',
           size = 2.7) +
  geom_segment(aes(x = 100, y = 90, 
                   xend = 650, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 1.05,
               color = "blue") +
  annotate("text", x = 1030, y = 90, label = "90% emergence", 
           fontface = 'italic',
           size = 2.7) +
  theme_few() +
  theme(axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9),
        legend.position = c(0.8, 0.25),
        legend.text = element_text(size = 5),
        legend.key.size = unit(0.3, "cm")) -> fig2

ggsave("figures/fig_5.png")
```


```{r}
readxl::read_excel("MT_Germ-Compiled.xlsx", sheet = "Weather Yr1") %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  rename(
    temp_high = c,
    temp_low = c_2,
    rel_hum = percent,
    precip = mm,
    wind_sp = m_s,
    soil_temp = c_10cm
  ) %>% 
  dplyr::select(-mj_m_2, -mm_2, -time) %>% 
  unite("date", c("year", "month", "day"), sep = "-") %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  mutate_if(is_character, as.double) -> wd_lcn1

readxl::read_excel("MT_Germ-Compiled.xlsx", sheet = "Weather Yr2") %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  rename(
    temp_high = c,
    temp_low = c_2,
    rel_hum = percent,
    precip = mm,
    wind_sp = m_s,
    soil_temp = c_10cm
  ) %>% 
  dplyr::select(-mj_m_2, -mm_2, -time) %>% 
  unite("date", c("year", "month", "day"), sep = "-") %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  mutate_if(is_character, as.double) -> wd_lcn2


wd_lcn1 %>% 
  bind_rows(wd_lcn2) %>% 
  mutate(mean_temp = (temp_high + temp_low) / 2) %>% 
  pivot_longer(cols = c("mean_temp", "soil_temp"), 
               names_to = "type", values_to = "temp") -> wd_lcn
```

```{r}
ylim.prim <- c(0, 180)   # in this example, precipitation
ylim.sec <- c(-27, 36)    # in this example, temperature

b <- diff(ylim.prim)/diff(ylim.sec)
a <- ylim.prim[1] - b*ylim.sec[1] # there was a bug here
```


```{r}
wd_lcn %>% 
  mutate(type = fct_recode(type,
                           "Air temperature (C)" = "mean_temp",
                           "Soil temperature (C)" = "soil_temp")) %>% 
  ggplot(aes(x = date, y = a + temp*b)) +
  geom_rect(mapping=aes(xmin= as.Date("2016-09-01"), xmax= as.Date("2017-04-30"),
                        ymin= 0, ymax= 160), 
            fill = "#FFFDD0", alpha=0.05) + 
  annotate("text", x=as.Date("2017-01-01"), y = 155, 
           label = "Year 1", face = "bold", 
           family = "roboto",
           size = 2, color = "black") + 
  geom_rect(mapping=aes(xmin= as.Date("2017-09-01"), xmax= as.Date("2018-06-20"),
                        ymin= 0, ymax= 160), 
            fill = "#FFFDD0", alpha=0.05) + 
  annotate("text", x=as.Date("2018-02-01"), y = 155, 
           label = "Year 2", face = "bold", 
           family = "roboto",
           size = 2, color = "black") + 
  geom_point(aes(color = type), size = 1, alpha = 0.5) +
  geom_line(aes(color = type, linetype = type), size = .3) +
  scale_color_manual(name = NULL, values = c("blue", "firebrick")) +
  scale_shape_manual(name = NULL, values = c(18, 16)) +
  scale_linetype_manual(name = NULL, values = c(3, 1)) +
  scale_y_continuous(
    "Precipitation (mm)", 
    sec.axis = sec_axis(~ (. - a)/b, name = "Temperature (C)")) +
  scale_x_date(date_minor_breaks = "1 day", date_labels = "%b %Y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_bar(aes(x = date, y = precip, 
               width = 3,
               linetype = NULL, 
               shape = NULL), 
           stat = "identity", 
           fill = "grey10",
           show.legend = FALSE) +
  annotate("text", x=as.Date("2017-01-20"), y = 10, 
           label = "Precipitation",
           size = 2, color = "grey10") +
  annotate("text", x=as.Date("2017-01-15"), y = 135, 
           label = "Mean\n air \ntemperature",
           size = 2, color = "blue") +
  annotate("text", x=as.Date("2018-01-15"), y = 135, 
           label = "Mean\n soil \ntemperature",
           size = 2, color = "firebrick") +
  labs(x = NULL) +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9)) -> fig3

ggsave("figures/fig_6.png")
```




```{r}
fig3 + fig2 -> figg

fig_st <- figg / fig1 +
  plot_annotation(title = "<b style='color:darkgreen;'>Horseweed</b> emergence in corn and soybean at Lincoln, NE",
       subtitle = "Comulative emergence was recorded from Sep 2016 to Apr 2017 (Year 1) and Sep 2017 to Jun 2018 (Year 2)",
       theme = theme(plot.title = element_markdown(hjust = 0, 
                                                   family = "roboto",
                                                   size = 15),
                     plot.subtitle = element_markdown(family = "roboto",
                                                      size = 10),
                     plot.title.position = "plot")) 

ggsave("figures/lincoln.png", width = 7)
```




# North Platte

```{r}
readxl::read_excel("Emergence.xlsx", sheet = "North Platte") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - May 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "North Platte") %>% 
  filter(!is.na(GDD)) -> np1
```


```{r}
readxl::read_excel("Emergence.xlsx", sheet = "North Platte") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(5:8) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - May 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin1" = "Lincoln",
                                 "Npl1" = "North Platte",
                                 "Scb1" = "Scottsbluff")) %>% 
  mutate(location = "North Platte") %>% 
  filter(!is.na(GDD)) -> np2
```



```{r}
np1 %>% 
  bind_rows(np2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> north_platte
```




```{r message = FALSE, warning = FALSE}
model3 <- drm(emergence ~ GDD, trt, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = north_platte)
```

```{r}
plot(model3)
```


```{r}
broom::tidy(model3) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

  
```{r}
ED(model3, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed3
```

```{r}
EDcomp(model3, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```


```{r}
ed3 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10% emergence",
  ed == "50" ~ "50% emergence",
  ed == "90" ~ "90% emergence",
  TRUE ~ "ed")) %>% 
  ggplot(aes(x = population, y = estimate, color = trt)) +
  geom_point(position = position_dodge(width = 0.7)) +
  geom_linerange(aes(ymin = lower, ymax = upper), 
                 position = position_dodge(width = 0.7)) +
  labs(x = NULL, y = "Growing degree days") +
  scale_color_brewer(palette = "Dark2") +
#  scale_color_viridis_d(name = NULL, option = "C") +
  facet_grid(~ ed, switch = "y") +
  coord_flip() +
  theme_few() +
#  scale_y_continuous(limits = c(0, 1500)) +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9),
        strip.text = element_markdown(face = "italic"),
        plot.title.position = "plot",
        plot.title = element_markdown(),
        plot.subtitle = element_markdown(size = 10)) -> fig7

ggsave("figures/fig_7.png", dpi = 300)
```




```{r Control prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(1500), length=1500)))
newdata1 <- data.frame(trt =c("Lin1 in soybean"), newdata)
newdata2 <- data.frame(trt =c("Lin1 in wheat stubble"), newdata)
newdata3 <- data.frame(trt =c("Npl1 in soybean"), newdata)
newdata4 <- data.frame(trt =c("Npl1 in wheat stubble"), newdata)
newdata5 <- data.frame(trt =c("Scb1 in soybean"), newdata)
newdata6 <- data.frame(trt =c("Scb1 in wheat stubble"), newdata)

nd=rbind(newdata1, newdata2, newdata3, newdata4, newdata5, newdata6)

pm <- predict(model3, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

north_platte$GDD0 <- north_platte$GDD
north_platte$GDD0[north_platte$GDD0==0] <- 0.5
```


```{r Control Plot, message=FALSE, warning=FALSE}
north_platte %>% 
ggplot(aes(x = GDD, y = emergence, color = trt)) + 
  geom_line(data = nd, aes(x = GDD, y = p, color = trt), size = 1.2) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
#  coord_trans(x= "log") +
  geom_jitter(data = north_platte, aes(x = GDD, y = emergence, color = trt),
              alpha = 0.1) +
  scale_color_brewer(name = NULL, palette = "Dark2") +
#  scale_color_viridis_d(name = NULL, option = "C") +
  geom_segment(aes(x = 0.5, y = 10, 
                   xend = 200, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 1.05,
               color = "blue") +
  annotate("text", x = 510, y = 10, label = "10% emergence", 
           fontface = 'italic',
           size = 2.7) +
  geom_segment(aes(x = 50, y = 50, 
                   xend = 400, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 1.05,
               color = "blue") +
  annotate("text", x = 710, y = 50, label = "50% emergence", 
           fontface = 'italic',
           size = 2.7) +
  geom_segment(aes(x = 350, y = 90, 
                   xend = 1350, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 1.05,
               color = "blue") +
  annotate("text", x = 1250, y = 80, label = "90% \nemergence", 
           fontface = 'italic',
           size = 2.7) +
  theme_few() +
  theme(axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9),
        legend.position = c(0.75, 0.2),
        legend.text = element_text(size = 5),
        legend.key.size = unit(0.3, "cm")) -> fig8

ggsave("figures/fig_8.png")
```


```{r}
readxl::read_excel("NorthPlatteWeatherDataMarestailStudy.xlsx") %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  rename(
    temp_high = c,
    date = na,
    temp_low = c_2,
    rel_hum = percent,
    precip = mm,
    wind_sp = m_s,
    soil_temp = c_10cm
  ) %>% 
  dplyr::select(-mj_m_2, -mm_2, -na_2) %>% 
  unite("date", c("year", "month", "day"), sep = "-") %>% 
  mutate(date = lubridate::ymd(date)) %>% 
  mutate_if(is_character, as.double) %>% 
  mutate(mean_temp = (temp_high + temp_low) / 2) %>% 
  pivot_longer(cols = c("mean_temp", "soil_temp"), 
               names_to = "type", values_to = "temp") -> wd_npt
```

```{r}
ylim.prim <- c(0, 180)   # in this example, precipitation
ylim.sec <- c(-27, 36)    # in this example, temperature

b <- diff(ylim.prim)/diff(ylim.sec)
a <- ylim.prim[1] - b*ylim.sec[1] # there was a bug here
```


```{r}
wd_npt %>% 
  filter(date < as.Date("2017-07-15")) %>% 
  mutate(type = fct_recode(type,
                           "Air temperature (C)" = "mean_temp",
                           "Soil temperature (C)" = "soil_temp")) %>% 
  ggplot(aes(x = date, y = a + temp*b)) +
  geom_rect(mapping=aes(xmin= as.Date("2016-09-01"), xmax= as.Date("2017-05-30"),
                        ymin= 0, ymax= 160), 
            fill = "#FFFDD0", alpha=0.05) + 
  annotate("text", x=as.Date("2017-01-01"), y = 155, 
           label = "Year 1", face = "bold", 
           family = "roboto",
           size = 2, color = "black") + 
  geom_point(aes(color = type), size = 1, alpha = 0.5) +
  geom_line(aes(color = type, linetype = type), size = .3) +
  scale_color_manual(name = NULL, values = c("blue", "firebrick")) +
  scale_shape_manual(name = NULL, values = c(18, 16)) +
  scale_linetype_manual(name = NULL, values = c(3, 1)) +
  scale_y_continuous(
    "Precipitation (mm)", 
    sec.axis = sec_axis(~ (. - a)/b, name = "Temperature (C)")) +
  scale_x_date(date_minor_breaks = "1 day", date_labels = "%b %Y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  geom_bar(aes(x = date, y = precip, 
               width = 3,
               linetype = NULL, 
               shape = NULL), 
           stat = "identity", 
           fill = "grey10",
           show.legend = FALSE) +
  annotate("text", x=as.Date("2016-08-30"), y = 70, 
           label = "Precipitation",
           size = 2, color = "grey10") +
  annotate("text", x=as.Date("2017-01-15"), y = 130, 
           label = "Mean soil \ntemperature",
           size = 2, color = "firebrick") +
  annotate("text", x=as.Date("2017-01-05"), y = 10, 
           label = "Mean air temperature",
           size = 2, color = "blue") +
  labs(x = NULL) +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 10),
        axis.text = element_markdown(size = 9)) -> fig9

ggsave("figures/fig_9.png")
```



```{r}
fig9 + fig8 -> figg

fig_np <- figg / fig7 +
  plot_annotation(title = "<b style='color:darkgreen;'>Horseweed</b> emergence in wheat stubble and soybean at North Platte, NE",
       subtitle = "Horseweed accessions comulative emergence was recorded from Sep 2016 to May 2017",
       theme = theme(plot.title = element_markdown(hjust = 0, 
                                                   family = "roboto",
                                                   size = 15),
                     plot.subtitle = element_markdown(family = "roboto",
                                                      size = 10))) 

ggsave("figures/north_platte.png", width = 7)
```

