---
title: "north_plate_2"
author: "Maxwel Coura Oliveira"
date: "10/1/2021"
output: html_document
---

```{r}
library(tidyverse)
library(drc)
library(reactable)
library(ggthemes)
library(ggtext)
library(patchwork)
library(ggrepel)
```

```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "North Platte") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - May 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "North Platte") %>% 
  filter(!is.na(GDD)) -> np1
```


```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "North Platte") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(5:8) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - May 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "North Platte") %>% 
  filter(!is.na(GDD)) -> np2
```



```{r}
np1 %>% 
  bind_rows(np2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> north_platte
```

## Wheat stubble


```{r message = FALSE, warning = FALSE}
wheat_m <- north_platte |> 
  filter(type == "wheat stubble")

model3 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = wheat_m)
```

```{r}
plot(model3, type = "all")
```


  
```{r}
ED(model3, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) -> ed3
```

```{r}
EDcomp(model3, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```

```{r warning = FALSE}
ed3 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10% emergence",
  ed == "50" ~ "50% emergence",
  ed == "90" ~ "90% emergence",
  TRUE ~ "ed")) |> 
  mutate(crop = "Wheat stubble") -> ed4
```


## Soybean


```{r message = FALSE, warning = FALSE}
soy_m <- north_platte |> 
  filter(type == "soybean")

model4 <- drm(emergence ~ GDD, population, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = soy_m)
```

```{r}
plot(model4, type = "all")
```


  
```{r}
ED(model4, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  mutate_if(is_character, as_factor) -> ed5
```

```{r}
EDcomp(model4, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```

```{r warning = FALSE}
ed5 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10% emergence",
  ed == "50" ~ "50% emergence",
  ed == "90" ~ "90% emergence",
  TRUE ~ "ed")) |> 
  mutate(crop = "Soybean") -> ed6
```

```{r}
soy <- tibble(crop = 'Soybean')
```



```{r}
ed4 %>%
  bind_rows(ed6) |> 
ggplot(aes(x = trt, y = estimate, color = trt, shape = ed)) +
  geom_point(position = position_dodge2(width = 0.4), size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.03,
                 position = position_dodge2(width = 0.4)) +
  labs(x = NULL, y = "Horseweed emergence (Growing Degree Days)", shape = NULL) +
  scale_y_continuous(limits = c(0, 1500)) +
  facet_grid(crop ~ .) +
  coord_flip() +
  scale_color_colorblind(name = NULL) +
  scale_shape_manual(values = c(8,9,10)) +
  geom_text_repel(aes(label = round(estimate,0), 
                         x = trt, color = trt),
                    size = 3,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 4355) +
  geom_curve(data = soy, mapping = aes(x = 0.8, y = 68, xend = 0.7, yend = 98),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = 2, inherit.aes = FALSE) + 
  geom_text(data = soy, mapping = aes(x = 0.7, y = 108), label = "10% emergence", 
           hjust = 0, size = 2.5, fontface = "italic", inherit.aes = FALSE) +
  geom_curve(data = soy, mapping = aes(x = 1.94, y = 172, xend = 1.84, yend = 202),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = 2, inherit.aes = FALSE) +
  geom_text(data = soy, mapping = aes(x = 1.84, y = 212), label = "50% emergence", 
           hjust = 0, size = 2.5, fontface = "italic", inherit.aes = FALSE) +
  geom_curve(data = soy, mapping = aes(x = 3.09, y = 505, xend = 2.99, yend = 535),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = 2, inherit.aes = FALSE) + 
  geom_text(data = soy, mapping = aes(x = 2.99, y = 545), label = "90% emergence", 
           hjust = 0, size = 2.5, fontface = "italic", inherit.aes = FALSE) +
  geom_text(data = soy, mapping = aes(x = 3.4, y = 0), label = "North Platte", 
           hjust = 0, size = 4, fontface = "italic", inherit.aes = FALSE) +
  
  theme_bw() +
  theme(legend.position = "none",
        strip.text = element_markdown(size = 11, 
                                      face = "bold"),
        axis.title = element_markdown(size = 11),
        axis.text = element_markdown(size = 10)) -> fig7


ggsave("figures/fig_7.png", dpi = 300, width = 4, height = 7)
```


```{r}
soy <- tibble(crop = 'Wheat stubble')
soy1 <- tibble(crop = 'Soybean')
```

```{r}
ed4 %>%
  bind_rows(ed6) -> eds 

eds  |>  
ggplot(aes(x = ed, y = estimate, color = trt, shape = trt)) +
  geom_point(position = position_dodge2(width = 0.7), size = 2) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.03,
                 position = position_dodge2(width = 0.7)) +
  labs(x = "Cumulative emergence (%)", 
       y = "Growing Degree Days", shape = NULL) +
  scale_y_continuous(limits = c(0, 1500), breaks = seq(0, 1500, 500)) +
  coord_flip() +
  facet_grid(crop ~ .) +
  scale_color_colorblind(name = NULL) +
  scale_shape_manual(values = c(8,9,10)) +
  geom_text_repel(data = eds, mapping = aes(label = round(estimate,0), 
                         x = ed, color = trt),
                    size = 3,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.7),
                    seed = 312) +
  geom_curve(data = soy, mapping = aes(x = 0.7, y = 94, xend = 0.6, yend = 220),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = "#000000", inherit.aes = FALSE) + 
  geom_text(data = soy, mapping = aes(x = 0.6, y = 250), label = "Lin", 
           hjust = 0, size = 3.5, fontface = "bold", inherit.aes = FALSE,
           color = "#000000") +
  geom_curve(data = soy, mapping = aes(x = 2.0, y = 211, xend = 2.2, yend = 350),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = -0.3, color = "#E69F00", inherit.aes = FALSE) +
  geom_text(data = soy, mapping = aes(x = 2.2, y = 400), label = "Npl", 
           hjust = 0, size = 3.5, fontface = "bold", inherit.aes = FALSE,
           color = "#E69F00") +
  geom_curve(data = soy, mapping = aes(x = 3.2, y = 548, xend = 3.4, yend = 700),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = -0.3, color = "#56B4E9", inherit.aes = FALSE) + 
  geom_text(data = soy, mapping = aes(x = 3.4, y = 750), label = "Scb", 
           hjust = 0, size = 3.5, fontface = "bold", color = "#56B4E9", 
           inherit.aes = FALSE) +
  geom_text(data = soy1, mapping = aes(x = 0.6, y = 850), label = "North Platte", 
           hjust = 0, size = 4, fontface = "italic", inherit.aes = FALSE) +
  theme_bw() +
  theme(legend.position = "none",
        strip.text = element_markdown(size = 12, 
                                      face = "bold"),
        panel.grid = element_blank(),
        axis.title = element_markdown(size = 12),
        axis.text = element_markdown(size = 11)) +
  guides(color = "none") -> fig1

ggsave("figures/fig_7.png", dpi = 300, width = 4, height = 7)
```




## Curve Wheat stubble


```{r Control prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(1500), length=1500)))
newdata1 <- data.frame(population = c("Lin"), newdata)
newdata2 <- data.frame(population = c("Npl"), newdata)
newdata3 <- data.frame(population = c("Scb"), newdata)

nd <- rbind(newdata1, newdata2, newdata3)

pm <- predict(model3, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

wheat_m$GDD0 <- wheat_m$GDD
wheat_m$GDD0[wheat_m$GDD0==0] <- 0.5
```


## Curve Soybean


```{r Control prediction, include=FALSE}
newdata <-  expand.grid(GDD=exp(seq(log(0.5), log(1500), length=1500)))
newdata4 <- data.frame(population =c("Lin"), newdata)
newdata5 <- data.frame(population =c("Npl"), newdata)
newdata6 <- data.frame(population =c("Scb"), newdata)

nd1 <- rbind(newdata4, newdata5, newdata6)

pm1 <- predict(model4, newdata=nd1, interval="confidence")

nd1$p <- pm1[,1] 
nd1$pmin <- pm1[,2] 
nd1$pmax <- pm1[,3] 

soy_m$GDD0 <- soy_m$GDD
soy_m$GDD0[soy_m$GDD0==0] <- 0.5
```



```{r message=FALSE, warning=FALSE}
wheat_m |> 
  bind_rows(soy_m) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) -> full_dt1

nd |> 
  mutate(crop = "Wheat stubble") -> nd

nd1 |> 
  mutate(crop = "Soybean") -> nd1

nd |> 
  bind_rows(nd1) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) -> nd2
```


```{r message=FALSE, warning=FALSE}
full_dt1 %>% 
ggplot(aes(x = GDD, y = emergence, color = population)) + 
  geom_line(data = nd2, aes(x = GDD, y = p, color = population), size = 1) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
  coord_trans(x= "log") +
#  geom_point(alpha = 0.1) +
  geom_jitter(data = full_dt1, 
              aes(x = GDD, y = emergence, color = population),
              alpha = 0.1) +
  facet_grid(crop ~ .) +
  scale_x_continuous(limits = c(1, 5000), breaks = c(1, 10, 100, 1000)) + 
  scale_color_colorblind(name = NULL, 
                         guide = guide_legend(reverse = TRUE)) +
  geom_segment(aes(x = 25, y = 10,
                   xend = 400, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 0.8,
               color = 2) +
  annotate("text", x = 700, y = 10, label = "10%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 70, y = 50, 
                   xend = 750, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 1350, y = 50, label = "50%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 200, y = 90, 
                   xend = 2000, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = 2) +
  annotate("text", x = 3500, y = 90, label = "90%", 
           fontface = 'italic', color = "#333333",
           size = 3) +
  theme_bw() +
  theme(axis.title = element_markdown(size = 12),
        axis.text = element_markdown(size = 11),
        legend.position = c(0.1, 0.95),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        panel.grid = element_blank(),
        legend.text = element_markdown(size = 8, face = "bold"),
        legend.key.size = unit(0.5, "cm"),
        strip.text = element_markdown(size = 12, face = "bold")) -> fig3

ggsave("figures/fig_22.png", dpi = 300, width = 4, height = 7)
```



## Weed density

```{r}
library(glmmTMB)
library(emmeans)
library(multcomp)
```


```{r}
readxl::read_excel("anova.xlsx", sheet = "NP") %>% 
  mutate_if(is_character, as_factor) %>% 
  rename(rep = R,
         pop = P,
         treat = `T`,
         time = S) %>% 
  mutate(trt = case_when(
    pop == "L" & treat == "dry" ~ "Lin in wheat stubble",
    pop == "NP" & treat == "dry" ~ "Npl in wheat stubble",
    pop == "SB" & treat == "dry" ~ "Scb in wheat stubble",
    pop == "L" & treat == "ir" ~ "Lin in soybean",
    pop == "NP" & treat == "ir" ~ "Npl in soybean",
    pop == "SB" & treat == "ir" ~ "Scb in soybean",
    TRUE ~ NA_character_
  )) %>% 
  separate("trt", c("population", "crop"), sep = " in ") |> 
  mutate(rep = as_factor(rep)) -> np_data
```

## Wheat stubble

```{r}
wt_m <- np_data |> 
  filter(crop == "wheat stubble")


mod_3 = glmmTMB(density ~ population * time + (1|rep),
                family = poisson(), data = wt_m)
```

```{r}
glmmTMB:::Anova.glmmTMB(mod_3)
```

```{r}
emmeans(mod_3, ~ population * time, type = "response") -> em_3
```


```{r}
cld(em_3, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE) %>% 
  as_tibble() |> 
  mutate(crop = "Wheat stubble") -> cld_3
```


## Soybean

```{r}
sb_m <- np_data |> 
  filter(crop == "soybean")


mod_4 = glmmTMB(density ~ population * time + (1|rep),
                family = poisson(), data = sb_m)
```

```{r}
glmmTMB:::Anova.glmmTMB(mod_4)
```

```{r}
emmeans(mod_4, ~ population, type = "response") -> em_4
```


```{r}
cld(em_4, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE) %>% 
  as_tibble() |> 
  mutate(crop = "Soybean") |> 
  mutate(time = "springfall") -> cld_4
```


```{r}
emmeans(mod_4, ~ time, type = "response") -> em_4_4
```


```{r}
cld(em_4_4, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE) %>% 
  as_tibble() |> 
  mutate(crop = "Soybean") |> 
  dplyr::select(1, 2, 5, 6) |> 
  mutate_if(is.double, ~round(.,2)) |> 
  mutate(rate = if_else(rate == 94.58, "94.58 a", "2.00 b")) |> 
  mutate(time = str_to_title(time)) |> 
  rename(Timing = time,
         Density = rate,
         `Lower CI` = lower.CL,
         `Upper CI` = upper.CL) -> cld_4_4
```

```{r}
weat <- tibble(crop = 'Wheat stubble')
```

```{r}
d <- tibble(x = c(1.95, 1.95), y = c(1.95, 1.95),
            name = c("A"), tb = list(cld_4_4), crop = "Soybean")
```

```{r}
scales::show_col(calc_pal()(4))
```

```{r}
library(ggpmisc)
cld_3 %>% 
  bind_rows(cld_4) |> 
  mutate(population = fct_recode(population,
    "<b style='color:#000000;'>Lin</b>" = "Lin",
    "<b style='color:#E69F00;'>Npl</b>" = "Npl",
    "<b style='color:#56B4E9;'>Scb</b>" = "Scb"
  )) -> cld_33
```





```{r}
cld_33 |> 
ggplot(aes(x = population, y = rate, 
             color = time, shape = time)) +
  geom_point(position = position_dodge2(width = 0.4, reverse = TRUE),
             size = 2) +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL), size = 1.03,
                 position = position_dodge2(width = 0.4, reverse = TRUE)) +
  labs(x = NULL, 
       y = expression(paste("Horseweed density (plants experimental unit"^"-1",")")),
       shape = NULL) +
  facet_grid(crop ~ .) +
  scale_y_continuous(limits = c(0, 420), breaks = seq(0, 420, 100)) +
  scale_shape_manual(values = c(16,15,14)) +
  geom_text_repel(aes(label = round(rate,0), 
                         x = population, color = time),
                    size = 3,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4, reverse = TRUE),
                    seed = 275) +
  scale_color_manual(values = c("#004586", "#ff420e", "#579d1c")) +
  geom_table_npc(data = d, aes(npcx = x, npcy = y, label = tb)) +
  geom_curve(data = weat, mapping = aes(x = 1.85, y = 10, xend = 1.7, yend = 15),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = "#ff420e", inherit.aes = FALSE) + 
  geom_text(data = weat, mapping = aes(x = 1.7, y = 20), label = "Spring", 
           hjust = 0, size = 3.5, fontface = "italic",
           color = "#ff420e", inherit.aes = FALSE) +
  geom_curve(data = weat, mapping = aes(x = 2.05, y = 337, xend = 1.9, yend = 360),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = "#004586", inherit.aes = FALSE) +
  geom_text(data = weat, mapping = aes(x = 1.9, y = 370), label = "Fall", 
           hjust = 0, size = 3.5, fontface = "italic", color = "#004586",
           inherit.aes = FALSE) +
  geom_curve(data = soy1, mapping = aes(x = 1.95, y = 21, xend = 1.8, yend = 80),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = "#579d1c", inherit.aes = FALSE) +
  geom_text(data = soy1, mapping = aes(x = 1.8, y = 90), label = "Nested across Timing", 
           hjust = 0, size = 3.5, fontface = "italic", color = "#579d1c",
           inherit.aes = FALSE) +
  geom_curve(data = soy1, mapping = aes(x = 2.95, y = 100, xend = 2.8, yend = 120),
             arrow = arrow(length = unit(0.07, "inch")), 
             size = 0.4, curvature = 0.3, color = "gray60", inherit.aes = FALSE) +
  geom_text(data = soy1, mapping = aes(x = 2.8, y = 130), label = "Nested across Population", 
           hjust = 0, size = 3.5, fontface = "italic", color = "gray60",
           inherit.aes = FALSE) +
  coord_flip() +
  geom_text(aes(x = population, y = upper.CL + 25, label = .group),
           position = position_dodge2(width = 0.4, reverse = TRUE)) +
  theme_bw() +
  theme(legend.position = "none",
        strip.text = element_markdown(size = 12, 
                                      face = "bold"),
        axis.title = element_markdown(size = 12),
        panel.grid = element_blank(),
        axis.text.y = element_markdown(size = 11))  -> fig2


ggsave("figures/fig_11.png", dpi = 300, width = 4, height = 7)
```




```{r warning = FALSE}
fig3 + fig1 + fig2 +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 15, hjust = 0, vjust = 0),
        panel.background = element_rect(fill = "#F5F5F5"),
        plot.background = element_rect(fill = "#F5F5F5"))

ggsave("figures/north_platte.png", width = 13, height = 7)
```





