---
title: "emergence"
author: "Maxwel Coura Oliveira"
date: "8/25/2021"
output: html_document
---

```{r}
library(tidyverse)
library(drc)
library(reactable)
library(ggthemes)
library(ggtext)
library(patchwork)
library(ggrepel)
```

# Scottsbluff

```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(1:4) %>% 
  pivot_longer(cols = 2:4, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2016 - Apr 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") %>% 
  filter(!is.na(GDD)) -> sctbf1
```


```{r}
readxl::read_excel("data/Emergence.xlsx", sheet = "SCOTTSBLUFF") %>% 
  janitor::row_to_names(row_number = 1) %>% 
  dplyr::select(7:13) %>% 
  pivot_longer(cols = 2:7, names_to = "type", values_to = "emergence") %>% 
  mutate(date = "Sep 2017 - Dec 2017") %>% 
  mutate_at(c("GDD", "emergence"),  as.double) %>% 
  mutate_at(c("GDD", "emergence"), ~ round(., 2)) %>% 
  separate("type", c("population", "type"), sep = "-") %>% 
  mutate_at(c("population", "type"), str_squish) %>% 
  mutate(population = fct_recode(population,
                                 "Lin" = "Lincoln",
                                 "Npl" = "North Platte",
                                 "Scb" = "Scottsbluff")) %>% 
  mutate(location = "Scottsbluff") -> sctbf2
```


```{r}
sctbf1 %>% 
  bind_rows(sctbf2) %>% 
  mutate(type = str_to_lower(type)) %>% 
  mutate(type = fct_recode(type,
                           "corn" = "irrigated")) |> 
  unite("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
  drop_na() -> scottsbluff
```

```{r message = FALSE, warning = FALSE}
model1 <- drm(emergence ~ GDD, trt, 
              fct = W1.3(fixed = c(NA, 100, NA), 
                         names = c("slope", "upper", "ed50")),
              data = scottsbluff)
```

```{r}
plot(model1)
```

```{r}
broom::tidy(model1) %>% 
  mutate_if(is.double, ~ round(., 2)) %>% 
  reactable()
```

```{r}
ED(model1, c(10, 50, 90), type = "absolute", interval = "delta") %>% 
  as.data.frame() %>% 
  rownames_to_column(., var = "name") %>% 
  as_tibble() %>% 
  separate(name, c("param", "trt", "ED"), sep = ":") %>% 
  janitor::clean_names() %>% 
  separate("trt", c("population", "type"), sep = " in ", remove = FALSE) %>% 
#  mutate(location = str_to_title(location)) %>% 
  mutate_if(is_character, as_factor) -> ed1
```

```{r}
EDcomp(model1, c(90,90), type = "absolute", 
       interval = "delta", level = 0.95)
```

```{r}
readxl::read_excel("data/dates.xlsx", sheet = "Scottsbluff") %>% 
  drop_na() %>% 
  mutate(month = lubridate::month(date),
         doy = lubridate::yday(date)) -> date_sct
```
 
 
 
```{r warning = FALSE}
ed1 %>% 
  mutate(ed = case_when(
  ed == "10" ~ "10% emergence",
  ed == "50" ~ "50% emergence",
  ed == "90" ~ "90% emergence",
  TRUE ~ "ed")) %>% 
  mutate(trt = fct_relevel(trt, levels = c("Lin in corn",
                                           "Scb in fallow",
                                           "Lin in fallow",
                                           "Npl in fallow",
                                           "Npl in corn",
                                           "Scb in corn"))) -> ed2
```


```{r}
ed2 %>% 
ggplot(aes(x = trt, y = estimate, color = trt, shape = ed)) +
  geom_point(position = position_dodge2(width = 0.4)) +
  geom_linerange(aes(ymin = lower, ymax = upper),
                 position = position_dodge2(width = 0.4)) +
  labs(x = NULL, y = "Growing degree days", shape = NULL) +
  scale_y_continuous(limits = c(0, 220)) +
  coord_flip() +
  scale_color_brewer(palette = "Paired") +
  scale_shape_manual(values = c(8,9,10)) +
  geom_text_repel(data = ed2, mapping = aes(label = round(estimate,0), 
                         x = trt, color = trt),
                    size = 2.5,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 455) +
  
  theme_few() +
  theme(legend.position = c(0.17, 0.1),
        legend.direction = "vertical",
        legend.text = element_markdown(size = 6, lineheight = 0.3),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(0.4, "cm"),
        axis.title = element_markdown(size = 12),
        axis.text = element_markdown(size = 11)) +
  guides(color = "none") -> fig1
```

```{r}
ed2 %>% 
ggplot(aes(x = population, y = estimate, color = population)) +
  geom_point(position = position_dodge2(width = 0.4), size = 2) +
  facet_grid(ed ~ type) +
  geom_linerange(aes(ymin = lower, ymax = upper), size = 1.1,
                 position = position_dodge2(width = 0.4)) +
  coord_flip() +
  scale_color_colorblind() +
  labs(x = NULL, y = "Growing degree days") +
  theme_bw() +
  geom_text_repel(data = ed2, mapping = aes(label = round(estimate,0), 
                         x = population, color = population),
                    size = 3,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 455) +
  theme(legend.position = "none",
        strip.text = element_markdown(size = 11, face = "bold"),
        axis.title = element_markdown(size = 12),
        axis.text = element_markdown(size = 11)) +
  guides(color = "none")

ggsave("figure/scotts2.png", width = 6, height = 8)
```


```{r}
geom_point(position = position_dodge2(width = 0.4)) +
  geom_linerange(aes(ymin = lower, ymax = upper),
                 position = position_dodge2(width = 0.4)) +
  labs(x = NULL, y = "Growing degree days", shape = NULL) +
  scale_y_continuous(limits = c(0, 220)) +
  coord_flip() +
  scale_color_brewer(palette = "Paired") +
  scale_shape_manual(values = c(8,9,10)) +
  geom_text_repel(data = ed2, mapping = aes(label = round(estimate,0), 
                         x = trt, color = trt),
                    size = 2.5,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 455) +
  
  theme_few() +
  theme(legend.position = c(0.17, 0.1),
        legend.direction = "vertical",
        legend.text = element_markdown(size = 6, lineheight = 0.3),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.key.size = unit(0.4, "cm"),
        axis.title = element_markdown(size = 12),
        axis.text = element_markdown(size = 11)) +
  guides(color = "none") -> fig1
fig1
```





```{r}
library(glmmTMB)
library(emmeans)
library(multcomp)
```


```{r}
readxl::read_excel("anova.xlsx", sheet = "SB") %>% 
  mutate_if(is_character, as_factor) %>% 
  rename(rep = R,
         pop = P,
         treat = `T`) %>% 
  mutate(trt = case_when(
    pop == "L" & treat == "dry" ~ "Lin in fallow",
    pop == "NP" & treat == "dry" ~ "Npl in fallow",
    pop == "SB" & treat == "dry" ~ "Scb in fallow",
    pop == "L" & treat == "ir" ~ "Lin in corn",
    pop == "NP" & treat == "ir" ~ "Npl in corn",
    pop == "SB" & treat == "ir" ~ "Scb in corn",
    TRUE ~ NA_character_
  )) %>% 
  mutate(rep = as_factor(rep)) -> sb_data
```


```{r}
mod_1 = glmmTMB(dansity ~ trt + (1|rep),
                family = poisson(), data = sb_data)
```

```{r}
glmmTMB:::Anova.glmmTMB(mod_1)
```

```{r}
emmeans(mod_1, ~ trt, type = "response") -> em_1
```


```{r}
cld(em_1, alpha=0.05, Letters=letters, adjust="none", reversed = TRUE) %>% 
  as_tibble() %>% 
  mutate(trt = fct_relevel(trt, levels = c("Lin in corn",
                                           "Scb in fallow",
                                           "Lin in fallow",
                                           "Npl in fallow",
                                           "Npl in corn",
                                           "Scb in corn"))) -> cld_1
```


```{r}
cld_1 %>% 
  ggplot(aes(x = fct_reorder(trt, rate), y = rate, color = trt)) +
  geom_point() +
  geom_linerange(aes(ymin = lower.CL, ymax = upper.CL)) +
  labs(x = NULL, y = expression(paste("Horseweed density (plants plot"^"-1",")"))) +
  scale_y_continuous(limits = c(0, 1100), breaks = seq(0, 1000, 200)) +
  geom_text_repel(aes(label = round(rate,0), 
                         x = trt, color = trt),
                    size = 2.5,
                    force_pull = 0,
                    direction = "y",
                    point.padding = NA,
                    min.segment.length = 14,
                    vjust = 0.5,
                    position = position_dodge2(width = 0.4),
                    seed = 455) +
  scale_color_brewer(palette = "Paired") +
#  facet_grid(~ ed, switch = "y") +
  coord_flip() +
  theme_few() +
  theme(legend.position = "none",
        axis.title = element_markdown(size = 12),
        axis.text = element_markdown(size = 11)) -> fig11

#ggsave("figures/fig_11.png", dpi = 300, width = 9)
```




```{r Control prediction, include=FALSE}
newdata <- expand.grid(GDD=exp(seq(log(0.5), log(760), length=760)))
newdata1 <- data.frame(trt =c("Lin in fallow"), newdata)
newdata2 <- data.frame(trt =c("Lin in corn"), newdata)
newdata3 <- data.frame(trt =c("Npl in fallow"), newdata)
newdata4 <- data.frame(trt =c("Npl in corn"), newdata)
newdata5 <- data.frame(trt =c("Scb in fallow"), newdata)
newdata6 <- data.frame(trt =c("Scb in corn"), newdata)

nd=rbind(newdata1, newdata2, newdata3, newdata4, newdata5, newdata6)

pm <- predict(model1, newdata=nd, interval="confidence")

nd$p <- pm[,1] 
nd$pmin <- pm[,2] 
nd$pmax <- pm[,3] 

scottsbluff$GDD0 <- scottsbluff$GDD
scottsbluff$GDD0[scottsbluff$GDD0==0] <- 0.5
```


```{r Control Plot, message=FALSE, warning=FALSE}
scottsbluff %>% 
    mutate(trt = fct_relevel(trt, levels = c("Lin in corn",
                                           "Scb in fallow",
                                           "Lin in fallow",
                                           "Npl in fallow",
                                           "Npl in corn",
                                           "Scb in corn"))) -> scottsbluff1

nd %>% 
    mutate(trt = fct_relevel(trt, levels = c("Lin in corn",
                                           "Scb in fallow",
                                           "Lin in fallow",
                                           "Npl in fallow",
                                           "Npl in corn",
                                           "Scb in corn"))) -> nd1
```


```{r message=FALSE, warning=FALSE}
scottsbluff1 %>% 
ggplot(aes(x = GDD, y = emergence, color = trt)) + 
  geom_line(data = nd1, aes(x = GDD, y = p, color = trt), size = 1) +
  labs(y="Cumulative emergence (%)", x = "Growing degree days") +
  coord_trans(x= "log") +
#  geom_point(alpha = 0.1) +
  geom_jitter(data = scottsbluff1, aes(x = GDD, y = emergence, color = trt),
              alpha = 0.1) +
  scale_x_continuous(limits = c(1, 1000), breaks = c(1, 10, 100, 1000)) + 
  scale_color_brewer(name = NULL, palette = "Paired",
                           guide = guide_legend(reverse = TRUE)) +
  geom_segment(aes(x = 30, y = 10,
                   xend = 120, yend = 10), 
               arrow = arrow(length = unit(0.03, "npc")), 
               size = 0.8,
               color = "#333333") +
  annotate("text", x = 200, y = 10, label = "10%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 50, y = 50, 
                   xend = 155, yend = 50), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = "#333333") +
  annotate("text", x = 280, y = 50, label = "50%", 
           fontface = 'italic',
           size = 3) +
  geom_segment(aes(x = 100, y = 90, 
                   xend = 255, yend = 90), 
               arrow = arrow(length = unit(0.03, "npc")),
               size = 0.8,
               color = "#333333") +
  annotate("text", x = 415, y = 90, label = "90%", 
           fontface = 'italic', color = "#333333",
           size = 3) +
  theme_few() +
  theme(axis.title = element_markdown(size = 12),
        axis.text = element_markdown(size = 11),
        legend.position = c(0.2, 0.9),
        legend.background = element_rect(colour = NA, fill = NA),
        legend.key = element_rect(colour = NA, fill = NA),
        legend.text = element_text(size = 7),
        legend.key.size = unit(0.3, "cm")) -> fig2
```



```{r warning = FALSE}
fig2 + fig1 + fig11 +
  plot_annotation(tag_levels = 'A') & 
  theme(plot.tag = element_text(size = 12, hjust = 0, vjust = 0))

ggsave("figures/scotts.png", width = 12)
```