---
title: "map"
author: "Maxwel Coura Oliveira"
date: "9/3/2021"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
```

```{r}
library(rnaturalearth)
library(rnaturalearthdata)

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)
```


```{r}
(sites <- tibble(location = c("Lincoln", "North Platte", "Scottsbluff"),
                 longitude = c(-96.7026, -100.7654, -103.6565), 
                 latitude = c(40.8136, 41.1239, 41.8670)))
```
```{r}
ggplot(data = world) +
    geom_sf() +
    geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = 23, fill = "darkred") +
    coord_sf(xlim = c(-110, -90), ylim = c(45, 33), expand = FALSE)
```
```{r}
library(maps)
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(states)
```


```{r}
states <- cbind(states, st_coordinates(st_centroid(states)))
```

```{r}
library(tools)
states$ID <- toTitleCase(states$ID)
head(states)
```


```{r}
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = NA) + 
    geom_text(data = states, aes(X, Y, label = ID), size = 5) +
    coord_sf(xlim = c(-105, -95), ylim = c(43.5, 39.5), expand = FALSE)
```


```{r}
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties <- subset(counties, grepl("nebraska", counties$ID))
counties$area <- as.numeric(st_area(counties))
head(counties)
```

```{r}
library(ggspatial)
ggplot(data = world) +
    geom_sf() +
    geom_sf(data = states, fill = "#EDEADE", color = "#EDEADE") + 
    geom_sf(data = counties, fill = "#FAF9F6", color = gray(.8)) +
    geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = c(22,21,23), fill = c(1,2,3)) +
#    geom_label(data = states, aes(X, Y, label = ID), size = 5, fontface = "bold", 
#        nudge_y = states$nudge_y) +
    geom_text(data = sites, aes(x = longitude, y = latitude, label = location),
              nudge_y = -0.2, color = "#333333", fontface = "bold") +
    labs(x = NULL, y = NULL) +
    annotation_scale(location = "bl", width_hint = 0.25) +
    annotation_north_arrow(location = "tr", which_north = "true", 
        pad_x = unit(0.1, "in"), pad_y = unit(0.1, "in"),
        style = north_arrow_nautical) +
    coord_sf(xlim = c(-104.25, -95.2), ylim = c(43.1, 39.9), expand = FALSE) #+
#  theme(plot.margin = unit(c(-6,0.3,-6,0.3), "cm"))

ggsave("map.png", width = 8, height = 4)
```

# USA

```{r}
usa <- subset(world, admin == "United States of America")
(mainland <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
    geom_sf(data = counties, fill = "cornsilk", color = gray(.5)) +
      geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = c(22,21,23), fill = c(1,2,3)) +
     coord_sf(crs = st_crs(2163), xlim = c(-2500000, 2500000), ylim = c(-2300000, 
         730000)))
```
```{r}
(alaska <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
     coord_sf(crs = st_crs(3467), xlim = c(-2400000, 1600000), ylim = c(200000, 
         2500000), expand = FALSE, datum = NA))
```
```{r}
(hawaii  <- ggplot(data = usa) +
     geom_sf(fill = "cornsilk") +
     coord_sf(crs = st_crs(4135), xlim = c(-161, -154), ylim = c(18, 
         23), expand = FALSE, datum = NA))
```
```{r}
mainland +
 annotation_custom(
      grob = ggplotGrob(alaska),
      xmin = -2750000,
      xmax = -2750000 + (1600000 - (-2400000))/2.5,
      ymin = -2450000,
      ymax = -2450000 + (2500000 - 200000)/2.5
  ) +
  annotation_custom(
      grob = ggplotGrob(hawaii),
      xmin = -1250000,
      xmax = -1250000 + (-154 - (-161))*120000,
      ymin = -2450000,
      ymax = -2450000 + (23 - 18)*120000
  )
```

```{r}
library(cowplot)
(ratioAlaska <- (2500000 - 200000) / (1600000 - (-2400000)))

## [1] 0.575

(ratioHawaii  <- (23 - 18) / (-154 - (-161)))

## [1] 0.7142857

ggdraw(mainland) +
    draw_plot(alaska, width = 0.26, height = 0.26 * 10/6 * ratioAlaska, 
        x = 0.05, y = 0.05) +
    draw_plot(hawaii, width = 0.15, height = 0.15 * 10/6 * ratioHawaii, 
        x = 0.3, y = 0.05)
```

